### ISSUE TITLE
layout_id_for_path/1 is undefined after following installation instructions

### ISSUE THREAD

**Issue by hubertpompecki** [BeaconCMS/beacon#131]
Hi, this project looks great and I'm excited to try it out! Unfortunately, following the [installation instructions](https://github.com/BeaconCMS/beacon/blob/main/guides/introduction/installation.md) doesn't seem to work right now and results in the following error:

```
UndefinedFunctionError at GET /my_site/home
function BeaconWeb.LiveRenderer.Page6A217F0F7032720EB50A1A2FBF258463.layout_id_for_path/1 is undefined (module BeaconWeb.LiveRenderer.Page6A217F0F7032720EB50A1A2FBF258463 is not available)
```

![image](https://user-images.githubusercontent.com/4353861/216814840-3436da5e-4e40-41f9-a6f7-173c6ce1a831.png)

This is true when adding beacon to an existing application as well as a new one when starting from scratch. I'm using:
* Elixir 1.14.3
* Phoenix 1.17.0-rc2

Logs:
```
[info] GET /my_site/home
[debug] Processing with BeaconWeb.PageLive.path/2
  Parameters: %{"path" => ["home"]}
  Pipelines: [:browser]
[debug] failed for the 1 time, retrying
[debug] failed for the 2 time, retrying
[debug] failed for the 3 time, retrying
[debug] failed for the 4 time, retrying
[debug] failed for the 5 time, retrying
[debug] failed for the 6 time, retrying
[debug] failed for the 7 time, retrying
[debug] failed for the 8 time, retrying
[debug] failed for the 9 time, retrying
[debug] failed for the 10 time, retrying
[debug] failed 10 times
[info] Sent 500 in 1160ms
[error] #PID<0.646.0> running Phoenix.Endpoint.SyncCodeReloadPlug (connection #PID<0.645.0>, stream id 1) terminated
Server: localhost:4000 (http)
Request: GET /my_site/home
** (exit) an exception was raised:
    ** (UndefinedFunctionError) function BeaconWeb.LiveRenderer.Page6A217F0F7032720EB50A1A2FBF258463.layout_id_for_path/1 is undefined (module BeaconWeb.LiveRenderer.Page6A217F0F7032720EB50A1A2FBF258463 is not available)
        BeaconWeb.LiveRenderer.Page6A217F0F7032720EB50A1A2FBF258463.layout_id_for_path(["home"])
        (beacon 0.1.0-dev) lib/beacon/loader.ex:41: Beacon.Loader.call_function_with_retry/4
        (beacon 0.1.0-dev) lib/beacon_web/live/page_live.ex:23: BeaconWeb.PageLive.mount/3
        (phoenix_live_view 0.18.11) lib/phoenix_live_view/utils.ex:335: anonymous fn/6 in Phoenix.LiveView.Utils.maybe_call_live_view_mount!/5
        (telemetry 1.2.1) /Users/hubert/code/my_app/deps/telemetry/src/telemetry.erl:321: :telemetry.span/3
        (phoenix_live_view 0.18.11) lib/phoenix_live_view/static.ex:278: Phoenix.LiveView.Static.call_mount_and_handle_params!/5
        (phoenix_live_view 0.18.11) lib/phoenix_live_view/static.ex:119: Phoenix.LiveView.Static.render/3
        (phoenix_live_view 0.18.11) lib/phoenix_live_view/controller.ex:39: Phoenix.LiveView.Controller.live_render/3
        (phoenix 1.7.0-rc.2) lib/phoenix/router.ex:425: Phoenix.Router.__call__/5
        (my_app 0.1.0) lib/my_app_web/endpoint.ex:1: MyAppWeb.Endpoint.plug_builder_call/2
        (my_app 0.1.0) lib/plug/debugger.ex:136: MyAppWeb.Endpoint."call (overridable 3)"/2
        (my_app 0.1.0) lib/my_app_web/endpoint.ex:1: MyAppWeb.Endpoint.call/2
        (phoenix 1.7.0-rc.2) lib/phoenix/endpoint/sync_code_reload_plug.ex:22: Phoenix.Endpoint.SyncCodeReloadPlug.do_call/4
        (plug_cowboy 2.6.0) lib/plug/cowboy/handler.ex:11: Plug.Cowboy.Handler.init/2
        (cowboy 2.9.0) /Users/hubert/code/my_app/deps/cowboy/src/cowboy_handler.erl:37: :cowboy_handler.execute/2
        (cowboy 2.9.0) /Users/hubert/code/my_app/deps/cowboy/src/cowboy_stream_h.erl:306: :cowboy_stream_h.execute/3
        (cowboy 2.9.0) /Users/hubert/code/my_app/deps/cowboy/src/cowboy_stream_h.erl:295: :cowboy_stream_h.request_process/3
        (stdlib 4.0.1) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
```

**Comment by hubertpompecki** [comment]
I see that this is because `priv/repo/beacon_seeds.exs` isn't run on `mix setup` unless the `ecto.setup` alias is modified in `mix.exs`.

Here's my attempt at modifying the installation mix task to fix this https://github.com/BeaconCMS/beacon/pull/132

**Comment by leandrocp** [comment]
Fixed by https://github.com/BeaconCMS/beacon/pull/132
