### ISSUE TITLE
Migration error on initial setup

### ISSUE THREAD

**Issue by supernintendo** [BeaconCMS/beacon#192]
I'm getting the following error when trying to install Beacon for a new Phoenix project:

```
19:49:09.252 [info] Migrations already up

19:49:09.314 [info] == Running 20230216191145 Beacon.Repo.Migrations.ChangePagesMetaTagsToArrayMap.up/0 forward

19:49:09.316 [debug] QUERY OK db=0.4ms
  SELECT id, meta_tags AS old_meta_tags FROM beacon_pages
 []
** (Protocol.UndefinedError) protocol Enumerable not implemented for nil of type Atom. This protocol is implemented for the following type(s): DBConnection.PrepareStream, DBConnection.Stream, Date.Range, Ecto.Adapters.SQL.Stream, File.Stream, Function, GenEvent.Stream, HashDict, HashSet, IO.Stream, Jason.OrderedObject, List, Map, MapSet, Phoenix.LiveView.LiveStream, Postgrex.Stream, Range, Stream
    (elixir 1.14.2) lib/enum.ex:1: Enumerable.impl_for!/1
    (elixir 1.14.2) lib/enum.ex:166: Enumerable.reduce/3
    (elixir 1.14.2) lib/enum.ex:4307: Enum.map/2
    deps/beacon/priv/repo/migrations/20230216191145_change_pages_meta_tags_to_array_map.exs:24: anonymous fn/3 in Beacon.Repo.Migrations.ChangePagesMetaTagsToArrayMap.up/0
    (elixir 1.14.2) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
    deps/beacon/priv/repo/migrations/20230216191145_change_pages_meta_tags_to_array_map.exs:19: Beacon.Repo.Migrations.ChangePagesMetaTagsToArrayMap.up/0
    (ecto_sql 3.10.1) lib/ecto/migration/runner.ex:289: Ecto.Migration.Runner.perform_operation/3
    (stdlib 4.0) timer.erl:235: :timer.tc/1
```

This is after following the steps here and using `mix beacon.install` - https://github.com/BeaconCMS/beacon/blob/main/guides/introduction/installation.md

**Comment by leandrocp** [comment]
Hi @supernintendo I just pushed a fix, please give it a try.
