### ISSUE TITLE
Error setting up new project as README.md

### ISSUE THREAD

**Issue by Talleyrand-34** [BeaconCMS/beacon#678]
### Environment

* Elixir version (elixir -v): Elixir 1.16.3 (compiled with Erlang/OTP 26)
* Phoenix version (mix deps): 1.7.14
* Phoenix LiveView version (mix deps):
* Beacon version (mix deps):
* Operating system: fedora 40
* Browsers on which you attempted to reproduce this bug (the more the merrier):

### Actual behavior
I did 
```log
mix archive.install hex phx_new && mix archive.install hex igniter_new
```
and then 
```log
mix igniter.new my_app --install beacon,beacon_live_admin --with phx.new --beacon.site my_site
* creating my_app/lib/my_app/application.ex
* creating my_app/lib/my_app.ex
* creating my_app/lib/my_app_web/controllers/error_json.ex
* creating my_app/lib/my_app_web/endpoint.ex
* creating my_app/lib/my_app_web/router.ex
* creating my_app/lib/my_app_web/telemetry.ex
* creating my_app/lib/my_app_web.ex
* creating my_app/mix.exs
* creating my_app/README.md
* creating my_app/.formatter.exs
* creating my_app/.gitignore
* creating my_app/test/support/conn_case.ex
* creating my_app/test/test_helper.exs
* creating my_app/test/my_app_web/controllers/error_json_test.exs
* creating my_app/lib/my_app/repo.ex
* creating my_app/priv/repo/migrations/.formatter.exs
* creating my_app/priv/repo/seeds.exs
* creating my_app/test/support/data_case.ex
* creating my_app/lib/my_app_web/controllers/error_html.ex
* creating my_app/test/my_app_web/controllers/error_html_test.exs
* creating my_app/lib/my_app_web/components/core_components.ex
* creating my_app/lib/my_app_web/controllers/page_controller.ex
* creating my_app/lib/my_app_web/controllers/page_html.ex
* creating my_app/lib/my_app_web/controllers/page_html/home.html.heex
* creating my_app/test/my_app_web/controllers/page_controller_test.exs
* creating my_app/lib/my_app_web/components/layouts/root.html.heex
* creating my_app/lib/my_app_web/components/layouts/app.html.heex
* creating my_app/lib/my_app_web/components/layouts.ex
* creating my_app/priv/static/images/logo.svg
* creating my_app/lib/my_app/mailer.ex
* creating my_app/lib/my_app_web/gettext.ex
* creating my_app/priv/gettext/en/LC_MESSAGES/errors.po
* creating my_app/priv/gettext/errors.pot
* creating my_app/priv/static/robots.txt
* creating my_app/priv/static/favicon.ico
* creating my_app/assets/js/app.js
* creating my_app/assets/vendor/topbar.js
* creating my_app/assets/css/app.css
* creating my_app/assets/tailwind.config.js

Fetch and install dependencies? [Yn]
* running mix deps.get
* running mix assets.setup
* running mix deps.compile

We are almost there! The following steps are missing:

    $ cd my_app

Then configure your database in config/dev.exs and run:

    $ mix ecto.create

Start your Phoenix app with:

    $ mix phx.server

You can also run your app inside IEx (Interactive Elixir) as:

    $ iex -S mix phx.server

     warning: Macro.Env.define_alias/4 is undefined or private
     │
 178 │       case Macro.Env.define_alias(env, meta, arg, [trace: false] ++ opts) do
     │                      ~
     │
     └─ lib/spitfire/env.ex:178:22: Spitfire.Env.expand/3
     └─ lib/spitfire/env.ex:481:28: Spitfire.Env.alias_defmodule/3

     warning: Macro.Env.define_import/4 is undefined or private
     │
 209 │            {:ok, env} <- Macro.Env.define_import(env, meta, arg, [trace: false] ++ opts) do
     │                                    ~
     │
     └─ lib/spitfire/env.ex:209:36: Spitfire.Env.expand/3

     warning: Macro.Env.define_require/4 is undefined or private
     │
 193 │       case Macro.Env.define_require(env, meta, arg, [trace: false] ++ opts) do
     │                      ~
     │
     └─ lib/spitfire/env.ex:193:22: Spitfire.Env.expand/3

     warning: Macro.Env.expand_alias/4 is undefined or private
     │
 137 │     case Macro.Env.expand_alias(env, meta, list, trace: false) do
     │                    ~
     │
     └─ lib/spitfire/env.ex:137:20: Spitfire.Env.expand/3

     warning: Macro.Env.expand_import/5 is undefined or private
     │
 308 │     case Macro.Env.expand_import(env, meta, fun, arity,
     │                    ~
     │
     └─ lib/spitfire/env.ex:308:20: Spitfire.Env.expand/3

     warning: Macro.Env.expand_require/6 is undefined or private
     │
 274 │       case Macro.Env.expand_require(env, meta, module, fun, arity,
     │                      ~
     │
     └─ lib/spitfire/env.ex:274:22: Spitfire.Env.expand/3


== Compilation error in file lib/swoosh/adapters/xml/helpers.ex ==
** (ArgumentError) lib file xmerl/include/xmerl.hrl could not be found
    (elixir 1.16.3) lib/record/extractor.ex:41: Record.Extractor.from_lib_file/1
    (elixir 1.16.3) lib/record/extractor.ex:18: Record.Extractor.from_or_from_lib_file/1
    (elixir 1.16.3) lib/record/extractor.ex:5: Record.Extractor.extract/2
    lib/swoosh/adapters/xml/helpers.ex:5: (module)
could not compile dependency :swoosh, "mix compile" failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile swoosh --force", update it with "mix deps.update swoosh" or clean it with "mix deps.clean swoosh"
==> swoosh
Compiling 51 files (.ex)

== Compilation error in file lib/swoosh/adapters/xml/helpers.ex ==
** (ArgumentError) lib file xmerl/include/xmerl.hrl could not be found
    (elixir 1.16.3) lib/record/extractor.ex:41: Record.Extractor.from_lib_file/1
    (elixir 1.16.3) lib/record/extractor.ex:18: Record.Extractor.from_or_from_lib_file/1
    (elixir 1.16.3) lib/record/extractor.ex:5: Record.Extractor.extract/2
    lib/swoosh/adapters/xml/helpers.ex:5: (module)
could not compile dependency :swoosh, "mix compile" failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile swoosh --force", update it with "mix deps.update swoosh" or clean it with "mix deps.clean swoosh"
```

### Expected behavior

Compile

### Additional considerations

I am a newbie in the elixir world. Assume i make a silly mistake.

**Comment by leandrocp** [comment]
Hi @Talleyrand-34 that bug is related to `swoosh` compilation (a Phoenix dependency). I found these 2 issues very similar to your problem: https://github.com/swoosh/swoosh/issues?q=xmerl.hrl

You're on OTP 26 which is supported but if you installed it with a system package, then you might need to install https://packages.fedoraproject.org/pkgs/erlang/erlang-xmerl/ as well

**Comment by leandrocp** [comment]
Hi @Talleyrand-34 I'm closing this one since it doesn't look to be caused by Beacon but feel free to re-open it. Thanks!
